river: Cannon
station: Welch

author: Andy Wickert

data:
    # Filename expected with columns "Q", "Stage"
    filename: 'CannonWelch05355200_RatingCurve_2002-2012.tsv'
    # tab, space, or comma
    delimiter: 'tab'
    # If data set uses US cfs (Q) and feet (Stage), converts these to metric.
    us-units: True

channel:
    # meters; if ommitted, will be solved for as a free variable
    width: 45
    # meters; if omitted, will be solved for as a free variable
    # Here, set to be just above the surveyed floodplain-channel-like form
    # depth: 0.7
    # unitless
    slope: 9E-4
    # Use depth instead of hydraulic radius for calculations. True/False.
    use_depth: False

bounds:
    # Uncomment the following to set them different from the defaults
    # They should be given in LOWER, UPPER
    mannings_n_bounds:
        - 0.020
        - 0.055
    # floodplain_coeff_bounds:
    #    - LOWER
    #    - UPPER
    floodplain_exponent_bounds:
        - 1.6666666666666666666667
        - 5
    stage_offset_bounds:
        - -2
        - 2
    channel_depth_bounds:
        - 2
        - 3
    #channel_width_bounds:
    #    - 40
    #    - 50

output:
    # CSV output file name
    outfile: 'doublemanning_params_CannonWelch.csv'
    # True/False Boolean flags
    plot: True
    verbose: True

