river: Cannon
station: Welch

author: Andy Wickert

data:
    # Filename expected with columns "Q", "Stage"
    filename: 'CannonWelch05355200_RatingCurve_2002-2012.tsv'
    # tab, space, or comma
    delimiter: 'tab'
    # If data set uses US cfs (Q) and feet (Stage), converts these to metric.
    us-units: True

channel:
    # meters; if ommitted, will be solved for as a free variable
    width: 45
    # meters; if omitted, will be solved for as a free variable
    # Here, set to be just above the surveyed floodplain-channel-like form
    # depth: 0.7
    # unitless
    slope: 9E-4
    # Use depth instead of hydraulic radius for calculations. True/False.
    use_depth: False

bounds:
    # Uncomment the following to set them different from the defaults
    # They should be given in LOWER, UPPER
    mannings_n_bounds:
        - 0.020
        - 0.055
    # floodplain_coeff_bounds:
    #    - LOWER
    #    - UPPER
    floodplain_exponent_bounds:
        - 1.6666666666666666666667
        - 5
    stage_offset_bounds:
        - -2
        - 2
    channel_depth_bounds:
        # Lidar data (banks, water surface) with info from stage offset
        # now, water surface when the lidar was acquired, and absolute
        # gauge elevation, tells us that the banks are 2.17 +/- 0.33 m (or so)
        # in total height from bed to floodplain
        - 1.84
        - 2.49
    #channel_width_bounds:
    #    - 40
    #    - 50


plotting:
    # If this is present, the plot will be saved.
    # Format set by file extension.
    # Path may be relative or absolute
    savepath: 'CannonRiver_Welch.pdf'
    # True/False Boolean flag
    show: True
    # Optional fixed plotting bounds
    stage_min: -0.001
    stage_max: 4.7
    #discharge_min: 
    discharge_max: 600
    # Plot curve even if discharge is negative (nonphysical)
    display_negative_rating_curve: False


output:
    # CSV output file name
    outfile: 'doublemanning_params_CannonWelch.csv'
    # True/False Boolean flag
    verbose: True

